=== DaisukeBekki/JSeM/data/v1.0/jsem.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT jsem-dataset (problem|comment)+>

<!-- miscellaneous comment, not necessarily on a specific problem -->
<!ELEMENT comment (#PCDATA)>

<!ELEMENT problem (link?,description?,p+,q?,h,a?,note*)>

<!-- problem -->
<!ATTLIST problem
  jsem_id CDATA #REQUIRED
  answer (yes|no|unknown|undef|unacceptable|weakacceptable|infelicitous) #REQUIRED
  jsem_nonstandard (true) #IMPLIED
  language (fa|de|zh|jp) #REQUIRED
  phenomena CDATA #IMPLIED
  inference_type (entailment|presupposition|CI|GCI|PCI) #IMPLIED
  >
<!--  inference_type CDATA -->

<!-- link element shows the information of corresponding FraCaS entry -->
<!ELEMENT link (#PCDATA)>
<!ATTLIST link
  resource CDATA #REQUIRED
  link_id CDATA #REQUIRED
  translation (yes|no|unknown) #IMPLIED
  same_phenomena (yes|no|unknown) #IMPLIED
  >

<!ELEMENT description (#PCDATA)>

<!-- premise elements, possibly more than one -->
<!ELEMENT p (script,english*)>
<!ATTLIST p
          idx (1|2|3|4|5) #REQUIRED>

<!-- question element, optional -->
<!ELEMENT q (script,english*)>

<!-- hypothesis element -->
<!ELEMENT h (script,english*)>

<!-- miscellaneous note or comment about problem -->
<!ELEMENT note (#PCDATA)>

<!-- translation in the target language script -->
<!ELEMENT script (#PCDATA)>

<!-- transliteration of the target language translation -->
<!ELEMENT translit (#PCDATA)>

<!--morphological representation of the target language -->
<!ELEMENT morph (#PCDATA)>

<!-- original English sentence in FraCaS test suite -->
<!ELEMENT english (#PCDATA)>

=== DaisukeBekki/JSeM/data/v1.0/Basics.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE jsem-dataset SYSTEM "jsem.dtd">
<?xml-stylesheet type="text/xsl" href="jsem.xsl"?>
<jsem-dataset>
  <problem answer="yes" inference_type="entailment"
  jsem_id="b01" language="jp"
  phenomena="Modifier">
    <description>《basic example》</description>
    <p idx="1">
      <script>太郎が緑色の茶を飲んだ。</script>
    </p>
    <h>
      <script>太郎が茶を飲んだ。</script>
    </h>
    <note></note>
  </problem>
</jsem-dataset>

=== DaisukeBekki/JSeM/data/anaphora/Disjunction.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE jsem-dataset SYSTEM "jsem.dtd">
<?xml-stylesheet type="text/xsl" href="jsem.xsl"?>
<jsem-dataset>
  <problem answer="other" inference_type="" jsem_id="D01" language="jp"
  phenomena="">
    <description></description>
    <p idx="1">
      <script>Either a woman walked in or she sat down.</script>
    </p>
    <h>
      <script>John sat down.</script>
    </h>
    <note></note>
  </problem>
  <problem answer="unknown" inference_type="" jsem_id="D01c" language="jp"
  phenomena="">
    <description></description>
    <p idx="1">
      <script>A woman walked in and she sat down.</script>
    </p>
    <h>
      <script>John sat down.</script>
    </h>
    <note></note>
  </problem>
  <problem answer="other" inference_type="" jsem_id="D02-a"
  language="jp" phenomena="">
    <description></description>
    <p idx="1">
      <script>Either a woman walked in or John sat down.</script>
    </p>
    <h>
      <script>She smiled.</script>
    </h>
    <note></note>
  </problem>
  <problem answer="unknown" inference_type="" jsem_id="D02-ac"
  language="jp" phenomena="">
    <description></description>
    <p idx="1">
      <script>A woman walked in and John sat down.</script>
    </p>
    <h>
      <script>She smiled.</script>
    </h>
    <note></note>
  </problem>
  <problem answer="other" inference_type="" jsem_id="D02-b"
  language="jp" phenomena="">
    <description></description>
    <p idx="1">
      <script>Either John sat down or a woman walked in.</script>
    </p>
    <h>
      <script>She smiled.</script>
    </h>
    <note></note>
  </problem>
  <problem answer="unknown" inference_type="" jsem_id="D02-bc"
  language="jp" phenomena="">
    <description></description>
    <p idx="1">
      <script>John sat down and a woman walked in.</script>
    </p>
    <h>
      <script>She smiled.</script>
    </h>
    <note></note>
  </problem>
  <problem answer="unknown" inference_type="" jsem_id="D03" language="jp"
  phenomena="">
    <description></description>
    <p idx="1">
      <script>A professor or an assistant professor will attend the meeting.</script>
    </p>
    <h>
      <script>She will report to the faculty.</script>
    </h>
    <note></note>
  </problem>
  <problem answer="unknown" inference_type="" jsem_id="D05" language="jp"
  phenomena="">
    <description></description>
    <p idx="1">
      <script>Either it is a holiday or a customer will come in.</script>
    </p>
    <h>
      <script>"If it is not a holiday, the customer will want to be served."</script>
    </h>
    <note></note>
  </problem>
  <problem answer="other" inference_type="" jsem_id="D05c" language="jp"
  phenomena="">
    <description></description>
    <p idx="1">
      <script>Either it is a holiday or a customer will come in.</script>
    </p>
    <h>
      <script>The customer will want to be served.</script>
    </h>
    <note></note>
  </problem>
</jsem-dataset>
